apiVersion: v1
data:
  key: S//Il4qdxmrfPbgOvFhvCr2EtkTbD8VfvBitS/vzJL4/dTumvQXv0Fi6XwE9I7Mt3HUnXtF0yeEzJxwJZjfmBWzOsNgWSw3Ejkaq3LDJkIIQg8aJkXD7Jqq/bVGP2jHF.x3NV17zK0iPOGSj9.hlOPDuzV0nBh4DUVWjeL5Q==
kind: Secret
metadata:
  annotations:
    version: f534779
  labels:
    appGroup: infra
    secret: myhelsana-infra
  name: spring-encrypt
type: Opaque
# kubesec:v:3
# kubesec:pgp:F4192D48D4DA978A4B262D53DD1DA34FC62DD71B:LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tCgpoUUVNQXp0N0s4c0tSem0wQVFnQWdvcitmcHZ0WithWEtQZjA2RVV3QXFOTU03eXJoTUZuK0x3cGZyS1NreTF1CkhIWldYb3cxUHNnMnIwSGM0L1FzRXhib0pFNTBMK09BZU54b05iT0FrdFlCTFl5bzRNUmIwc0pNWXBoWDNBVHYKTDl5Y3piKy9yYWJnYWRRYnhvcWVvRm1tWkRFeFRqbVU3SkdkQnF2dW02dGJtMURORFZXWlZjSCt6RmJCQlBpKwowZlJpUi9rT3ZnejdsSmltdk8xVEhhei9tVWlRNHQ2TEZOTjdNVTlTV1dvbkJwemxId25xTzlVejNEbndad3VUCnMwSkxyclFOUDVMUlhITm5mV0NsZlBMVXJ1YlB6ZXVNTkpybjdSRzREcjVscEd3cnlTT1JlR3oxVXpQYjJFQ1kKMjdDWmxVV0I2SzFoenZNeGoreFUvejlDc2J2elgyVG5tT3VabzZLRFFkTEE3QUhLaWVVOTZuT1F6TmNIVEZocgpPUHdBYU91WlpuZ3lqR1JyWEN6eVNPWldlMUxpbFV3YmcrN0grSitoOTJ2YVVOU1huY2E2Wm9TQXRwMEY1R1NvCkhpazMrSURCeWp6ei9xZDR2dXdvZnlNUE0vMVJsZlZzN2NrQ0doUGNQamI4Nk9XZUVvMXYyeUp4SitkWW9rbXEKbmxJU3hxbFpTRzJKdHVmb0hUOCtuSk9IR3ZwMWNzVVNWQW03WUlUUXVZS0dOaU9jOGpJMU5sYkVuaDl4Zng5YwpucnY3WEh0d1VWVlZTbWs1VzRZb3RMb0V1SXNjbXh0bTBnYVloV2tPVWtSamF4WkZySkdJaGJsRmZTT0pudGtKCjFxSXRIcWJobzlYZ2twMEpiUkZlcEd0aml4SVUyU25RUWdqOFREUjN0K0Zmb1RTM3UwS1ZTOG95d3ByR1IwaEIKeTZzYlFQNHg0bzM1QVdaRW5PRkM2eGhpckdQZy9pSUMvb2d2NHB2OUJzNDUyd1Y4czBNalM5NXViL2xwY0dweQpoclVuWUNwcnRlaWNvUTNVb1p5V2lhMHVYZXk4cytZTVJDRXJHQ1ZTcityYklmeXl0TjRQemFYcVpncnh3aG9XCmNybGJHeWZhdzMrNzFpZlNvcDh6OXhEbUIxRFI1MEdPOWF6eDF4ZXJXYUYraHdxSkcvYkFDdjE0VnV2alpYNVMKRFFoL3diZ2luOGhOUlp5V3RobGZLT3NIVmdZRG53RDlGWENuMU1NMgo9VktnawotLS0tLUVORCBQR1AgTUVTU0FHRS0tLS0tCg==
# kubesec:mac:nWUIv+2SZ1VK8V/+.UMODQzIJd5QcSbxxKGa/zg==

