---
kind: Service
apiVersion: v1
metadata:
  name: spf
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
---
kind: Endpoints
apiVersion: v1
metadata:
  name: spf
subsets:
  - addresses:
      - ip: 192.168.1.106
      - ip: 10.44.66.36
    ports:
      - port: 9999
